### ISSUE TITLE
Why is there no timestep parameter during creating convlstm?

### ISSUE THREAD

**Issue by kaishijeng** [pengr97/ConvLSTM#1]
I didn't see timestep parameter in sample.py below:

       self.clstm = ConvLSTM(input_size=self.input_size,
                              input_dim=self.input_dim,
                              hidden_dim=self.hidden_dim,
                              kernel_size=self.kernel_size,
                              num_layers=self.num_layers,
                              padding=self.padding)
Doesn't ConvLSTM need this info?

**Comment by pengr97** [comment]
The shape of input is (batch, time_steps, channel, height, weight). The default number of blocks per ConvLSTM layer is time_steps. Therefore, no timestep parameter is required to initialize ConvLSTM, but you need to make sure the shape of input contains timestep.

**Comment by pengr97** [comment]
Thank you for your letter! The shape of input is (batch, time_steps,
channel, height, weight). The default number of blocks per ConvLSTM layer
is time_steps. Therefore, no timestep parameter is required to initialize
ConvLSTM, but you need to make sure the shape of input contains timestep.

kaishijeng <notifications@github.com> 于2020年4月1日周三 上午4:10写道：

**Comment by kaishijeng** [comment]
Thanks for the response.
